# ----------------------------
# Site Identity
# ----------------------------
title: "JKL2theBest — Личный сайт Мухаммета Суханкулиева"
email: "muhammet.jkl2.suhanguylev@gmail.com"
description: >-
  Персональный сайт Мухаммета Суханкулиева: DevOps, информационная безопасность, тестирование, CTF.
  Здесь вы найдете проекты, портфолио и контактную информацию.

baseurl: "" # оставить пустым если сайт на GitHub Pages без подкаталога
url: "https://jkl2thebest.github.io"

# ----------------------------
# Author Info (мета-данные)
# ----------------------------
author:
  name: "Мухаммет Суханкулиев"
  job_title: "DevOps / QA / Infosec"
  location: "Санкт-Петербург, Россия"
  email: "muhammet.jkl2.suhanguylev@gmail.com"
  telegram: "https://t.me/jkl2youtube"
  github: "https://github.com/JKL2theBest"

# ----------------------------
# Social media (иконки)
# ----------------------------
github_username: "JKL2theBest"
linkedin_username: ""
telegram_username: "jkl2youtube"
twitter_username: "" # если появится

# ----------------------------
# Build Settings
# ----------------------------
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

# ----------------------------
# SEO (jekyll-seo-tag)
# ----------------------------
seo:
  type: "Person"
  name: "Мухаммет Суханкулиев"
  url: "https://jkl2thebest.github.io"
  description: "Личный сайт, портфолио и учебные материалы JKL2theBest"
  twitter:
    username: ""
    card: "summary"
  social:
    name: "JKL2theBest"
    links:
      - "https://github.com/JKL2theBest"
      - "https://t.me/jkl2youtube"

# ----------------------------
# Exclusions (не компилировать)
# ----------------------------
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/

# ----------------------------
# Defaults (по умолчанию)
# ----------------------------
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Мухаммет Суханкулиев"
  -
    scope:
      path: ""
    values:
      layout: "default"

# ----------------------------
# Collections (если планируешь)
# ----------------------------
# collections:
#   projects:
#     output: true
#     permalink: /projects/:name/

# ----------------------------
# Custom variables (если потребуется)
# ----------------------------
# my_cv_url: "/assets/files/Sukhankuliev_M_CV.pdf"
