title: JKL2theBest  
email: muhammet.jkl2.suhanguylev@gmail.com  
description: >-
  Суханкулиев Мухаммет — студент ИТМО, факультет информационной безопасности.  

baseurl: ""  
url: "https://jkl2thebest.github.io"  

twitter_username: ""  
github_username: JKL2theBest  

theme: minima  
plugins:
  - jekyll-feed  

# Контакты и соцсети для удобства отображения на сайте  
social_links:  
  - name: GitHub  
    url: https://github.com/JKL2theBest  
  - name: Telegram  
    url: https://t.me/jkl2youtube  
  - name: Email  
    url: mailto:muhammet.jkl2.suhanguylev@gmail.com  

# Персональные данные для вывода (если шаблон поддерживает)  
author:  
  name: Суханкулиев Мухаммет  
  role: Студент ИТМО, Факультет Информационной Безопасности  
  location: Санкт-Петербург, Россия  
  contact_phone: "+7 (931) 535-5395"  

# Исключить из сборки (при необходимости)  
exclude:  
  - Gemfile  
  - Gemfile.lock  
  - node_modules/  
  - vendor/  

