title: "JKL2theBest — Личный сайт"
email: "muhammet.jkl2.suhanguylev@gmail.com"
description: >-
  Персональный сайт Мухаммета Суханкулиева: DevOps, информационная безопасность, тестирование, CTF.
  Здесь вы найдете проекты, портфолио и контактную информацию.

baseurl: ""
url: "https://jkl2thebest.github.io"

author_name: "Мухаммет Суханкулиев"
author_job_title: "DevOps / QA / Infosec"
author_location: "Санкт-Петербург, Россия"
author_email: "muhammet.jkl2.suhanguylev@gmail.com"
author_telegram: "https://t.me/jkl2youtube"
author_github: "https://github.com/JKL2theBest"

github_username: "JKL2theBest"
telegram_username: "jkl2youtube"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Мухаммет Суханкулиев"
  -
    scope:
      path: ""
    values:
      layout: "default"
